version: '3.8'

services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DB_URI}
      - AIRFLOW__CORE__LOAD_DEFAULT-CONNECTIONS=False
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY} 
    depends_on:
      - airflow_metadata
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
    networks:
      - airflow-networks

  airflow_metadata:
    image: postgres:latest
    container_name: airflow_metadata
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${AIRFLOW_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - airflow_metadata:/var/lib/postgresql/data
    networks:
      - airflow-networks

  flight_src_db:
    image: postgres:latest
    container_name: flight_src_db
    environment:
      POSTGRES_USER: ${FLIGHT_SRC_DB_USER}
      POSTGRES_PASSWORD: ${FLIGHT_SRC_DB_PASSWORD}
      POSTGRES_DB: ${FLIGHT_SRC_DB_NAME}
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${FLIGHT_SRC_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-networks
    volumes:
      - ./flight_src_db:/docker-entrypoint-initdb.d
      - flight_src_data:/var/lib/postgresql/data

  flight_wrh_db:
    image: postgres:latest
    container_name: flight_wrh_db
    environment:
      POSTGRES_USER: ${FLIGHT_WRH_DB_USER}
      POSTGRES_PASSWORD: ${FLIGHT_WRH_DB_PASSWORD}
      POSTGRES_DB: ${FLIGHT_WRH_DB_NAME}
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${FLIGHT_WRH_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-networks
    volumes:
      - ./flight_wrh_db:/docker-entrypoint-initdb.d
      - flight_wrh_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    container_name: minio
    hostname: minio
    restart: always
    volumes:
      - minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - airflow-networks

volumes:
  airflow_metadata:
    driver: local
    name: airflow_metadata

  flight_src_data:
    driver: local
    name: flight_src_data
  
  flight_wrh_data:
    driver: local
    name: flight_wrh_data

  minio_data:
    driver: local
    name: minio_data

networks:
  airflow-networks:
    driver: bridge

    
